
image: maven:3-jdk-11-slim

build:
  script:
    - mvn -B clean org.jacoco:jacoco-maven-plugin:0.8.3:prepare-agent install site:site -Dmaven.test.failure.ignore=true
    - mvn -B org.codehaus.mojo:sonar-maven-plugin:3.6.0.1398:sonar -Dsonar.gitlab.commit_sha=$CI_BUILD_REF -Dsonar.gitlab.ref_name=$CI_BUILD_REF_NAME
